"""arceau table maj

Revision ID: 05550d6b759c
Revises: a6fa26019620
Create Date: 2023-04-02 16:52:48.572653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05550d6b759c'
down_revision = 'a6fa26019620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arceau', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arceau', schema=None) as batch_op:
        batch_op.drop_column('action')

    # ### end Alembic commands ###
