"""arceau table

Revision ID: a6fa26019620
Revises: 
Create Date: 2023-04-01 19:15:47.285977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6fa26019620'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arceau',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('arceau_group', sa.Integer(), nullable=True),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arceau')
    # ### end Alembic commands ###
